[package]
name = "adventofsql"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = { version = "0.19.9", features = ["with-chrono-0_4"] }
rust_decimal = { version = "1.36.0", features = ["db-postgres"]}
chrono = "0.4.38"
